provider:
  default:
    language: 1.2
  digitalocean:
    language: 1.2

sources:
  - '**/*.nim'
  - '**/*.nimble'

binaries:
  - server

cloud:
  config:
    package_update: true
    runcmd:
      - systemctl disable cloud-init
      - systemctl enable web
      
service: |
  [Unit]
  Description=web

  [Service]
  Type=notify
  EnvironmentFile=/etc/web
  WorkingDirectory=/opt/web
  ExecStart=/opt/web/server

  [Install]
  WantedBy=multi-user.target
