provider:
  default:
    language: 2.7
  digitalocean:
    language: 2.7

environments:
  RACK_ENV: production

cloud:
  config:
    package_update: true
    packages:
      - "@development-tools"
      - "@rpm-development-tools"
      - ruby
      - ruby-devel
    runcmd:
      - systemctl disable cloud-init
      - systemctl enable web

command: /opt/web/bin/bundle exec /opt/web/bin/puma -C /opt/web/config/puma.rb

service: |
  [Unit]
  Description=Puma HTTP Server
  After=network.target

  [Service]
  Type=simple
  EnvironmentFile=/etc/web
  WorkingDirectory=/opt/web
  ExecStart={{{command}}}
  Restart=always

  [Install]
  WantedBy=multi-user.target
