provider:
  default:
    language: 2.7
  digitalocean:
    language: 2.7

environment:
  RACK_ENV: production
  BUNDLE_PATH: "/opt/web/vendor/bundle"
  
deps:
  - "@development-tools"
  - "@rpm-development-tools"
  - ruby
  - ruby-devel
  
bootstrap:
  - bundle config set without "development test"
  - bundle config set path "vendor/bundle"
  - bundle install
  - bundle binstubs puma
  - bundle binstubs bundler

command: /opt/web/bin/bundle exec /opt/web/bin/puma -C /opt/web/config/puma.rb
