provider:
  default:
    language: 8.8

sources:
  - '**/*.hs'
  - stack.yaml
  - '*.cabal' 

binaries:
  - .stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build/servant-proj-exe/servant-proj-exe

command: /opt/web/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build/servant-proj-exe/servant-proj-exe

docker_pause: 35
