framework:
  github: dutradda/apidaora
  version: 0.26

deps:
  - libffi-devel
  - curl

alpine-deps:
  - libffi-dev
  - openssl-dev

# install maturin to build orjson
# @see https://github.com/ijl/orjson/issues/8#issuecomment-570335365
after_command:
  - curl https://sh.rustup.rs > init.sh
  - sh init.sh -y
  - find $HOME/.cargo/bin -type f -exec install {} /usr/local/bin \;
  - cd /opt/web && python3 -m pip install -r requirements.txt -U

files:
  - server.py
  - requirements.txt
  - ../.config/gunicorn.py

environment:
  RUSTFLAGS: -C target-feature=-crt-static
  WORKER_CLASS: uvicorn.workers.UvicornWorker
  
