framework:
  github: lizhichao/one
  version: 2.0

before_command:
  - mkdir -p App/RunCache
  - chmod 777 App/RunCache

deps:
  - nginx
  - php
  - composer
  
files:
  - composer.json
  - public/index.php
  - ../.config/nginx.conf

bootstrap:
  - composer install --no-dev --prefer-dist --classmap-authoritative
  - composer dumpautoload -o
  - mv config/nginx.conf /etc/nginx/conf.d/default.conf
  - sed -i 's/;prefix.*/prefix = \/opt\/web\/public/g' /etc/php-fpm.d/www.conf
  - systemctl enable php-fpm
  - systemctl enable nginx
  - mkdir -p App/RunCache
  - chmod 777 App/RunCache
