framework:
  website: www.hyperf.io
  version: 1.1

php_ext:
  - redis
  - swoole

after_command:
  - echo "swoole.use_shortname = 'Off'" >> /etc/php.d/99-swoole.ini

bootstrap:
  - composer install --no-dev --prefer-dist --classmap-authoritative 
  - composer dumpautoload -o

command: /usr/bin/php /opt/web/sbin/hyperf.php start
