framework:
  website: jooby.io
  version: 2.8

image: gradle:6.1-jdk8

build:
- gradle clean shadowJar

command: >-
  /usr/bin/java -server
  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -XX:-UseBiasedLocking -XX:+UseStringDeduplication
  -jar /opt/web/build/libs/my-application.jar benchmark.AppKt
