framework:
  website: nette.org/en/
  version: 3.0

deps:
  - nginx
  - php
  - composer
  
files:
  - composer.json
  - '**/*.php'
  - ../.config/nginx.conf

bootstrap:
  - composer install --no-dev --prefer-dist --classmap-authoritative
  - composer dumpautoload -o
  - mv config/nginx.conf /etc/nginx/conf.d/default.conf
  - sed -i 's/;prefix.*/prefix = \/opt\/web\/public/g' /etc/php-fpm.d/www.conf
  - systemctl enable php-fpm
  - systemctl enable nginx
  - mkdir -p temp/cache
  - chmod 777 -R temp
