AllCops:

  Exclude:
    - Rakefile
    - "lib" # this is from crystal build

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/LineLength:
  Enabled: false

# rack-routing use method name for route handling
Naming/AccessorMethodName:
  Exclude:
    - ruby/rack-routing/app/route_handler.rb

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes


Metrics/BlockLength:
  Exclude:
    - '.spec/**'
