cloud:
  config:
    output:
      init:
          output: "> /var/log/cloud-init.out"
          error: "> /var/log/cloud-init.err"
      config: "tee -a /var/log/cloud-config.log"
      final:
          - ">> /var/log/cloud-final.out"
          - "/var/log/cloud-final.err"