provider:
  default:
    language: 2.8
  digitalocean:
    language: 2.8

files:
- main.dart
- pubspec.yaml

bootstrap:
- '[[ -f /etc/fedora-release ]] && dnf copr -y enable tcg/devel || true'
- '[[ -f /etc/fedora-release ]] && dnf -y install dart-bin || true'
- pub get

command: /usr/bin/dart /opt/web/main.dart
