provider:
  default:
    language: 2.8
  digitalocean:
    language: 2.8

files:
  - main.dart
  - pubspec.yaml

bootstrap:
  - dnf copr -y enable tcg/devel && dnf -y install dart-bin && pub get

command: /usr/bin/dart /opt/web/main.dart
