framework:
  website: ubiquity.kobject.net
  version: 2.3

deps:
  - nginx
  - php
  - php-pecl-zip
  - composer
  
files:
  - composer.json
  - '**/*.php'
  - ../.config/nginx-rewrite.conf

bootstrap:
  - composer update
  - chmod +x vendor/bin/Ubiquity
  - mkdir .ubiquity
  - mkdir app/cache -p
  - vendor/bin/Ubiquity bootstrap prod
  - rm -fr vendor
  - composer install --no-dev --prefer-dist --classmap-authoritative
  - composer dumpautoload -o
  - mv config/nginx-rewrite.conf /etc/nginx/conf.d/default.conf
  - sed -i 's/;prefix.*/prefix = \/opt\/web/g' /etc/php-fpm.d/www.conf
  - "[[ -f /etc/fedora-release ]] && systemctl enable php-fpm || true"
  - "[[ -f /etc/fedora-release ]] && systemctl enable nginx || true"
