framework:
  github: ray-ang/basicphp
  version: 0.9

deps:
  - nginx
  - php
  
files:
  - app.php
  - ../.config/nginx.conf

bootstrap:
  - mv config/nginx.conf /etc/nginx/conf.d/default.conf
  - sed -i 's/;prefix.*/prefix = \/opt\/web\/public/g' /etc/php-fpm.d/www.conf
  - rm -fr config
  - systemctl enable php-fpm
  - systemctl enable nginx 
