framework:
  website: amberframework.org
  version: 0.34
  
files:
  - server
  - config/application.cr
  - config/environments/development.yml
  - config/environments/production.yml
  - config/environments/test.yml
  - config/routes.cr
