provider:
  default:
    language: 13.14
  digitalocean:
    language: 12.16

files:
  - app.js
  - package.json
  - ../.config/ecosystem.config.js

environment:
  NODE_ENV: production
  PORT: 3000
  PM2_HOME: /root/.pm2

after_command:
  - npm -g install pm2

cloud:
  config:
    package_update: true
    packages:
      - "@development-tools"
      - nodejs
    runcmd:
      - cd /opt/web && npm install
      - systemctl disable cloud-init
      - systemctl enable web

command: /usr/local/bin/pm2-runtime /opt/web/config/ecosystem.config.js app

service: |
  [Unit]
  After=network.target

  [Service]
  Type=simple
  WorkingDirectory=/opt/web
  EnvironmentFile=/etc/web
  ExecStart={{{command}}}
  Restart=on-failure

  [Install]
  WantedBy=multi-user.target

# By default, we force a sleep on docker (or docker-machine)
docker_pause: 5
