framework:
  website: hug.rest
  version: 2.6
  
files:
  - server.py
  - requirements.txt
  - ../.config/gunicorn.py

environment:
  WORKER_CLASS: meinheld.gmeinheld.MeinheldWorker

command:  /usr/bin/python3.8 /usr/local/bin/gunicorn --log-level warning --reuse-port --log-syslog --chdir /usr/src/app -c /usr/src/app/config/gunicorn.py server:__hug_wsgi__
