framework:
  website: symfony.com
  version: 5.1

deps:
- nginx
- php
- composer

files:
- composer.json
- '**/*.yaml'
- '**/*.php'
- ../.config/nginx.conf

environment:
  APP_ENV: prod

bootstrap:
- composer install --no-dev --prefer-dist --classmap-authoritative
- composer dumpautoload -o
- mv config/nginx.conf /etc/nginx/conf.d/default.conf
- sed -i 's/;prefix.*/prefix = \/opt\/web\/public/g' /etc/php-fpm.d/www.conf
- '[[ -f /etc/fedora-release ]] && systemctl enable php-fpm || true'
- '[[ -f /etc/fedora-release ]] && systemctl enable nginx || true'
- mkdir -p var/log
- chown nginx var/log
- mkdir -p var/cache
- chown nginx var/cache
