framework:
  website: symfony.com
  version: 5.1
  
files:
  - ../.config/nginx.conf

deps:
  - nginx

environment:
  APP_ENV: prod

bootstrap:
  - mkdir -p var/log && chown nginx var/log
  - mkdir -p var/cache && chown nginx var/cache
