framework:
  github: twisted/klein
  version: 20.6
  
files:
  - requirements.txt
  - server.py

environment:
  PYTHONPATH: /usr/src/app

command: /usr/local/bin/twistd -n web --class=server.application --port=tcp:3000
