framework:
  website: iceframework.org
  version: 1.6

build_deps:
  - bash

php_ext:
  - ice

deps:
  - nginx
  - php
  - composer
  - php-pear
  - "@development-tools"
  - php-devel
  
files:
  - composer.json
  - '**/*.php'
  - ../.config/nginx-rewrite.conf

bootstrap:
  - composer install --no-dev --prefer-dist --classmap-authoritative
  - composer dumpautoload -o
  - mv config/nginx-rewrite.conf /etc/nginx/conf.d/default.conf
  - sed -i 's/;prefix.*/prefix = \/opt\/web\/public/g' /etc/php-fpm.d/www.conf 
  - systemctl enable php-fpm
  - systemctl enable nginx
