framework:
  github: nanoexpress/pro
  version: 1.11

environment:
  EXPERIMENTAL_FASTCALL: 1
  environment:
  NODE_ENV: production
  PORT: 3000

build_deps:
  - git

fixes:
  - ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
