framework:
  website: laravel.com
  version: 7.15

files:
  - app/**/*.php
  - bootstrap/app.php
  - composer.json
  - routes/web.php
  - public/index.php
  - ../.config/nginx.conf
  - ../.config/php-fpm.conf

deps:
  - nginx

environment:
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: base64:txfHNf/SOo222Rm8I39Urb9SmvUy+nuAF98t/ukF0lk=