framework:
  github: walkor/Workerman
  version: 4.0

php_mod:
  - pcntl
  - posix

deps:
  - php
  - php-posix
  - composer

bootstrap:
  - composer install --no-dev --prefer-dist --classmap-authoritative
  - composer dumpautoload -o

command: /usr/bin/php /opt/web/start.php start
