framework:
  website: nestjs.com
  version: 7.1

files:
  - nest-cli.json
  - src/**/*.ts
  - tsconfig.build.json
  - tsconfig.json
  - package.json
  - ../.config/ecosystem.config.js

bootstrap:
  - npm -g install pm2 && npm -g install @nestjs/cli && nest build && mv dist/*.js . && mv dist/*.map .
