provider:
  default:
    language: 5.2

sources:
  - "**/*.swift"

binaries:
  - .build

deps:
  - swift-lang-runtime

bootstrap:
  - find /usr/libexec/swift/lib/swift/linux -type f -name '*.so' -exec ln -sfv {} /usr/lib64 \;
  - ln -sfv /usr/libexec/swift/lib/swift/linux/libicui18nswift.so.61.2 /usr/lib64/libicui18nswift.so.61
  - ln -sfv /usr/libexec/swift/lib/swift/linux/libicuucswift.so.61 /usr/lib64/libicuucswift.so.61
  - ln -sfv /usr/libexec/swift/lib/swift/linux/libicudataswift.so.61 /usr/lib64/libicudataswift.so.61

command: /opt/web/.build/release/server
