provider:
  default:
    language: 1.10

files:
  - '**/*.ex'
  - '**/*.exs'
  - ../.script/compile.sh

environment:
  HOME: /opt/web

bootstrap:
  - bash script/compile.sh

deps:
  - elixir

command: /opt/web/release/bin/server start

