framework:
  website: kore.io
  version: 3.3

provider:
  default:
    language: 99

sources:
  - "**/*.c"
  - "**/*.conf"

download:
  - wget -c https://kore.io/releases/kore-3.3.1.tar.gz && tar xvf kore-3.3.1.tar.gz
  - cd kore-3.3.1 && TASKS=1 NOTLS=1 make && make install

build:
  - cd hello && kodev build

build_deps:
  - bsd-compat-headers
  - libressl-dev

bin_deps:
  - libressl

binaries:
  - ../../local/bin/kore
  - hello/hello.so

command: cd hello && /local/bin/kore -f -n -r -c conf/hello.conf