framework:
  github: an-tao/drogon
  version: 1.0

provider:
  default:
    language: 14/17

build_deps:
  - jsoncpp-dev
  - util-linux-dev
  - libressl-dev
  - zlib-dev

bin_deps:
  - jsoncpp 
  - libuuid
  - libressl
  - zlib

binaries:
  - build/drogon_benchmark

download:
  - git clone --branch v1.0.0-beta13 https://github.com/an-tao/drogon
  - cd /usr/src/app/drogon && git submodule update --init

build:
  - mkdir /usr/src/app/build
  - cd /usr/src/app/build && cmake -DCMAKE_BUILD_TYPE=release ..
  - cd /usr/src/app/build && make

files: 
  - config.json

command: build/drogon_benchmark config.json