framework:
  website: masoniteproject.com
  version: 2.3
 
files:
  - app/http/controllers/PageController.py
  - bootstrap/start.py
  - config/application.py
  - config/database.py
  - config/__init__.py
  - config/packages.py
  - config/providers.py
  - config/storage.py
  - requirements.txt
  - routes/web.py
  - wsgi.py
  - ../.config/gunicorn.py

deps:
  - libffi-dev

alpine-deps:
  - openssl-dev

environment:
  WORKER_CLASS: meinheld.gmeinheld.MeinheldWorker

command: /usr/local/bin/python /usr/local/bin/gunicorn --log-level warning --reuse-port --log-syslog --chdir /opt/web -c /opt/web/config/gunicorn.py wsgi
