provider:
  default:
    language: 8
  digitalocean:
    language: 8

sources:
  - src/**/*.java
  - src/**/*.properties
  - pom.xml

binaries:
  - target/*.jar

deps:
  - java-1.8.0-openjdk

docker_pause: 10
