framework:
  github: nanoexpress/nanoexpress
  version: 2.0

environment:
  EXPERIMENTAL_FASTCALL: 1
  NODE_ENV: production
  PORT: 3000

deps:
- '@development-tools'
- nodejs
- git

alpine-deps:
- git

alpine-fixes:
- ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2
