framework:
  website: rubyonrails.org
  version: 6.0

deps:
  - libxml2-devel
  - libxslt-devel

alpine-deps:
  - libxml2-dev
  - libxslt-dev


files:
  - Gemfile
  - config.ru
  - Rakefile
  - ../.config/puma.rb
  - app/controllers/*.rb
  - app/controllers/*.yml
  - config/*.rb
  - config/environments/*.rb
  - config/application.rb

docker_pause: 5
