framework:
  website: luminusweb.com
  version: 1.0

image: clojure:openjdk-11-lein-slim-buster

sources:
  - "**/*.clj"
  - "**/*.edn"
  - "**/logback.xml"
  - "**/*.html"

build:
  - lein uberjar

binaries:
  - target

command: /usr/bin/java -jar /opt/web/target/uberjar/luminus.jar 3000
