framework:
  website: luminusweb.com
  version: 1.0

image: clojure:openjdk-11-lein-slim-buster

build: 
  - lein uberjar

binaries:
  - /opt/web/target/uberjar/luminus.jar

command: /usr/bin/java -jar /opt/web/target/uberjar/luminus.jar 3000
