framework:
  website: github.com/emmett-framework/emmett
  version: 2.0

deps:
  - libffi-dev

alpine-deps:
  - openssl-dev

files:
  - server.py
  - requirements.txt
  - ../.config/gunicorn.py

environment:
  WORKER_CLASS: emmett.asgi.workers.EmmettWorker
