framework:
  website: github.com/emmett-framework/emmett
  version: 2.0

build_deps:
  - libffi-dev
  - openssl-dev

fixes:
  - pip install pendulum==2.0.5

files:
  - server.py
  - requirements.txt
  - ../.config/gunicorn.py

environment:
  WORKER_CLASS: emmett.asgi.workers.EmmettWorker
