framework:
  website: javalin.io
  version: 3.8

build: 
  - mvn compile assembly:single
  
binaries:
  - target/benchmark-0.0.1-SNAPSHOT-jar-with-dependencies.jar

command: >
  java -server 
  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts 
  -cp target/benchmark-0.0.1-SNAPSHOT-jar-with-dependencies.jar benchmark.javalin.Bench profiles=production
