framework:
  website: nestjs.com
  version: 7.1

files:
  - nest-cli.json
  - src/**/*.ts
  - tsconfig.build.json
  - tsconfig.json
  - package.json
  - ../.config/ecosystem.config.js

after_command:
  - npm -g install pm2
  - npm -g install @nestjs/cli
  - cd /opt/web && /usr/local/bin/nest build
  - mv /opt/web/dist/*.js /opt/web
  - mv /opt/web/dist/*.map /opt/web
