framework:
  github: ohler55/agoo
  version: 2.12

environment:
  AGOO_WORKER_COUNT: $(nproc)

command: /opt/web/bin/bundle exec /usr/bin/ruby /opt/web/app.rb

before_command:
  # Install bundler binstubs
  - cd /opt/web && bundle binstubs bundler

files:
  - app.rb
  - Gemfile
