framework:
  github: ohler55/agoo
  version: 2.12

environment:
  AGOO_WORKER_COUNT: $(nproc)

command: /usr/src/app/bin/bundle exec /usr/bin/ruby /usr/src/app/app.rb

before_command:
  # Install bundler binstubs
  - cd /usr/src/app && bundle binstubs bundler

files:
  - app.rb
  - Gemfile
