framework:
  website: micronaut.io
  version: 1.2

image: gradle:6.3

build:
  - gradle build --project-cache-dir ~/.gradle

patch:
  - USER root
  - RUN chown -R gradle /usr/src/app
  - USER gradle

sources:
  - src/**/*.java
  - build.gradle

binaries:
  - build/distributions/app-0.1.tar

files:
  - src/**/*.yml
  - src/**/*.xml

after_command:
  - tar -xvf build/distributions/app-0.1.tar

command: app-0.1/bin/app
