provider:
  default:
    language: 3.8
  digitalocean:
    language: 3.8

files:
  - requirements.txt
  - server.py
  
cloud:
  config:
    package_update: true
    package_upgrade: true
    packages:
      - build-essential
      - python3.8
      - python3.8-dev
      - python3-pip
    runcmd:
      - ln -sfv /usr/bin/python3.8 /usr/local/bin/python

      # Disable cloud-init to avoid re-run on reboot
      - systemctl disable cloud-init

      # Enable web so as application is started at startup
      - systemctl enable web

after_command:
  - cd /opt/web && /usr/local/bin/python -m pip install -r requirements.txt -U

command: /usr/local/bin/python /usr/local/bin/gunicorn --log-level warning --reuse-port --log-syslog --chdir /opt/web -c /opt/web/config/gunicorn.py server:app

# SystemD startup script
# This need to be tuned
# For security (do not run as root) ...
service: |

  [Unit]
  Description=gunicorn daemon
  After=network.target

  [Service]
  Type=notify
  WorkingDirectory=/opt/web
  EnvironmentFile=/etc/web
  ExecStart={{{command}}}
  ExecReload=/bin/kill -s HUP $MAINPID
  KillMode=mixed
  TimeoutStopSec=5
  PrivateTmp=true

  [Install]
  WantedBy=multi-user.target
