framework:
  github: lizhichao/one
  version: 2.0

php_ext:
  - swoole

command: /usr/bin/php /opt/web/App/swoole.php

bootstrap:
  - composer install --no-dev --prefer-dist --classmap-authoritative
  - composer dumpautoload -o
  
