provider:
  default:
    language: 1.4
  digitalocean:
    language: 1.4

files:
  - "**/*.jl"
  - Project.toml
  - Manifest.toml

deps:
  - julia

bootstrap:
  - julia deps.jl

command: /usr/bin/julia /opt/web/server.jl

docker_pause: 20
