<<<<<<< HEAD
provider:
  default:
    language: 1.5
  digitalocean:
    language: 1.5

files:
  - "**/*.jl"
  - Project.toml

docker_pause: 20

cloud:
  config:
    package_update: true
    packages:
      - julia
    runcmd:
      - systemctl disable cloud-init
      - systemctl enable web
      - "cd /opt/web && julia deps.jl"

command: /usr/bin/julia /opt/web/server.jl

service: |
  [Unit]
  Description=web
  After=network.target

  [Service]
  Type=simple
  EnvironmentFile=/etc/web
  WorkingDirectory=/opt/web
  ExecStart={{{command}}}
  Restart=always

  [Install]
  WantedBy=multi-user.target
=======
provider:
  default:
    language: 1.4
  digitalocean:
    language: 1.4

files:
  - "**/*.jl"
  - Project.toml
  - Manifest.toml

deps:
  - julia

bootstrap:
  - julia deps.jl

<<<<<<< HEAD
command: /usr/bin/julia /opt/web/server.jl

service: |
  [Unit]
  Description=web
  After=network.target

  [Service]
  Type=simple
  EnvironmentFile=/etc/web
  WorkingDirectory=/opt/web
  ExecStart={{{command}}}
  Restart=always

  [Install]
  WantedBy=multi-user.target
>>>>>>> 4db6aa6a... fix(julia): Missing files in container
=======
command: /usr/bin/julia /opt/web/server.jl
>>>>>>> 42596089... chore: Add gitignore per language
