framework:
  website: spring.io/projects/spring-boot
  version: 2.2

binaries:
  - target/benchmark-0.0.1-SNAPSHOT.jar

command: >
  java 
  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts 
  -jar target/benchmark-0.0.1-SNAPSHOT.jar
