provider:
  default:
    language: 5.30
  digitalocean:
    language: 5.30

files:
  - cpanfile
  - "**/*.psgi"

deps:
  - perl
  - perl-App-cpanminus

bootstrap:
  - cpanm --notest --installdeps .

command: /usr/local/bin/plackup -s Gazelle --port 3000 --env production --app d2app.psgi
