provider:
  default:
    language: 4.7

sources:
  - "**/*.fs"

binaries:
  - out

deps:
  - aspnetcore-runtime-3.1

environment:
  ASPNETCORE_URLS: http://+:3000
  COMPlus_TieredCompilation: 1

command: /usr/bin/dotnet /opt/web/out/web.dll
