provider:
  default:
    language: 4.7

sources:
  - '**/*.fs'

binaries:
  - out

environment:
  COMPlus_TieredCompilation: 1

deps:
  - aspnetcore-runtime-3.1

command: /usr/bin/dotnet /usr/src/app/out/web.dll
