provider:
  default:
    language: 1.3

sources:
  - "**/*.kt"
  - "**/*.gradle"
  - "**/*.properties"
  - "**/*.conf"

binaries:
  - build/libs/my-application.jar

docker_pause: 5

command: /usr/bin/java -server -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -XX:+AlwaysPreTouch -jar /opt/web/build/libs/my-application.jar

cloud:
  config:
    package_update: true
    packages:
      - java-11-openjdk
    runcmd:
      - systemctl disable cloud-init
      - systemctl enable web
      - mkdir -p /opt/web/build/libs/

service: |
  [Unit]
  Description=web
  After=network.target

  [Service]
  Type=simple
  EnvironmentFile=/etc/web
  WorkingDirectory=/opt/web
  ExecStart={{{command}}}
  Restart=always

  [Install]
  WantedBy=multi-user.target

