provider:
  default:
    language: 7.4
  digitalocean:
    language: 7.2

files:
  - src/**/*.php
  
deps:
  - php
  - php-fpm
  
boostrap:
  - mv /opt/web/config/nginx.conf /etc/nginx/conf.d/nginx.conf 
  - mv /opt/web/config/php-fpm.ini /etc/php/7.2/fpm/pool.d/www.conf
  - rm -fr /opt/web/config
