framework:
  website: cyclone.io
  version: 1.3

deps:
  - "@development-tools"
  - python3
  - python3-devel
  - python3-pip
  - libffi-devel

alpine-deps:
  - libffi-dev
  - openssl-dev

command: /usr/local/bin/twistd --python=server.py --nodaemon
